// Generated by FlutterFire — values extracted from google-services.json
// and GoogleService-Info.plist (project: bookmi-ea7a9).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LbywHNyRH7qJS7m8UB5j1BMZy0sDlgs',
    appId: '1:372395527538:web:1a3894eb332739e8b661eb',
    messagingSenderId: '372395527538',
    projectId: 'bookmi-ea7a9',
    storageBucket: 'bookmi-ea7a9.firebasestorage.app',
    measurementId: 'G-0069K1XH0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJaH4j0E2UE9QtHcVxmpFYJsbfS66MD6A',
    appId: '1:372395527538:android:172168f969077b86b661eb',
    messagingSenderId: '372395527538',
    projectId: 'bookmi-ea7a9',
    storageBucket: 'bookmi-ea7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOZBBEQYXRSdDhsLKxGCJ2n2VmpK9TeE',
    appId: '1:372395527538:ios:7ee55edec9f2d856b661eb',
    messagingSenderId: '372395527538',
    projectId: 'bookmi-ea7a9',
    storageBucket: 'bookmi-ea7a9.firebasestorage.app',
    iosBundleId: 'com.bookmi.app',
  );
}
